---

- name: install base homebrew packages
  homebrew:
    name: "{{item}}"
    state: latest
  with_items:
    - ansible
    - docker
    - docker-machine
    - git
    - hugo
    - iftop
    - jq
    - mtr
    - multirust
    - npm
    - openssl
    - packer
    - rbenv
    - sbt
    - terminal-notifier
    - terraform
    - tmux
    - tree

- name: install homebrew cask packages
  homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - atom
    - intellij-idea
    - java

- name: install gems
  gem:
    name: "{{item}}"
    state: latest
    user_install: no
  notify: rbenv rehash
  with_items:
    - bundler
    - jekyll

- name: install npm packages
  npm:
    name: "{{item}}"
    state: latest
    global: yes
  with_items:
    - keybase-installer

- name: install pathogen
  git: repo=https://github.com/tpope/vim-pathogen dest=~/.vim/vim-pathogen
  register: pathogen_install

- name: link pathogen
  file: src=~/.vim/vim-pathogen/autoload dest=~/.vim/autoload state=link
  when: pathogen_install

- name: install vim pathogen packages
  git: repo=https://github.com/{{ item.repo }} dest=~/.vim/bundle/{{ item.dest }}
  with_items:
    - { repo: 'scrooloose/syntastic', dest: 'syntastic' }
    - { repo: 'plasticboy/vim-markdown', dest: 'vim-markdown' }
    - { repo: 'tpope/vim-fugitive', dest: 'vim-fugitive' }
    - { repo: 'fatih/vim-go', dest: 'vim-go' }
    - { repo: 'rust-lang/rust.vim', dest: 'rust.vim' }
    - { repo: 'airblade/vim-gitgutter', dest: 'vim-gitgutter' }
    - { repo: 'derekwyatt/vim-scala', dest: 'vim-scala' }
    - { repo: 'rodjek/vim-puppet', dest: 'vim-puppet' }

