---

- name: install base homebrew packages
  homebrew:
    name: "{{item}}"
    state: latest
  with_items:
    - ansible
    - caskroom/cask/brew-cask
    - docker
    - docker-machine
    - git
    - iftop
    - jq
    - mtr
    - npm
    - openssl
    - packer
    - rbenv
    - rust
    - terminal-notifier
    - terraform
    - tmux
    - tree

- name: install homebrew cask packages
  homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - atom

- name: install gems
  gem:
    name: "{{item}}"
    state: latest
    user_install: no
  notify: rbenv rehash
  with_items:
    - bundler
    - jekyll

- name: install npm packages
  npm:
    name: "{{item}}"
    state: present
    global: yes
  with_items:
    - keybase-installer

- name: install vim pathogen packages
  git: repo=https://github.com/{{ item.repo }} dest=~/.vim/bundle/{{ item.dest }}
  with_items:
    - { repo: 'scrooloose/syntastic', dest: 'syntastic' }
    - { repo: 'plasticboy/vim-markdown', dest: 'vim-markdown' }
    - { repo: 'tpope/vim-fugitive', dest: 'vim-fugitive' }

