---

- name: install base homebrew packages
  homebrew:
    name: "{{item}}"
    state: present
  with_items:
    - ansible
    - git
    - openssl
    - rbenv
    - rbenv-gem-rehash
    - rust
    - tmux
    - tree

- name: install gems
  gem:
    name: "{{item}}"
    state: present
  with_items:
    - jekyll

