---

- name: install base homebrew packages
  homebrew:
    name: "{{item}}"
    state: present
  with_items:
    - ansible
    - caskroom/cask/brew-cask
    - git
    - mtr
    - npm
    - openssl
    - rbenv
    - rbenv-gem-rehash
    - rust
    - tmux
    - tree

- name: install gems
  gem:
    name: "{{item}}"
    state: present
    user_install: no
  notify: rbenv rehash
  with_items:
    - bundler
    - jekyll

- name: install npm packages
  npm:
    name: "{{item}}"
    state: present
    global: yes
  with_items:
    - keybase-installer

